﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿function basicTransaction(){
trace("여기는 basicTransaction입니다.");
  http.sync=true;
  Transaction("codeList","svcBase::code.do?method=findCodeList","","gds_code=gds_code","","callback");
//Transaction("식별이름(보통메서드명)","컨텍스트::요청주소","in데이터셋","gds_code=아웃데이터셋","개별변수","callback받을이름");
  Transaction("codeDetailList","svcBase::codeDetail.do?method=findCodeDetailList","","gds_codeDetail=gds_codeDetail","","callback");
  	transaction("findDeptList",
				"svcManagement::/dept.do?method=findDeptList",
				"",
				"gds_dept=gds_dept",
				"",
				"callback");
	 transaction("findPositiontList",
				"svcManagement::/position.do?method=findPositionList",
				"",
				"gds_position=gds_position",
				"",
				"callback");
				
 	transaction("findMenuList",
				"svcBase::/menu.do?method=findMenuList",
				"",
				"gds_menu=gds_menu",
				"",
				"callback");
	transaction("findEmployeeList",
				"svcEmp::employee.do?method=findEmployeeList",
				"",
				"gds_employee=gds_employee",
				"",
				"callback");
 	transaction("findWorkPlaceList",
				"svcManagement::workplace.do?method=findWorkplaceList",
				"",
				"gds_workplace=gds_workplace",
				"",
				"callback");
				http.sync=false;
	}